/**
 * HRPT page field name -> SPORDO internal `field_id` lookup.
 *
 * Deliberately kept small, separate, and data-only (per the task brief) so
 * it's trivial to update once branch `fix/hrpt-field-names` (a parallel
 * agent correcting stale HRPT names in FIELD_DATABASE, in
 * public/TrueSpordo.html) lands. Do NOT hardcode this mapping inline in the
 * sync/parser logic — always go through `resolveFieldId`.
 *
 * ## How current ids were derived
 *
 * FIELD_DATABASE's static `id` values are precomputed with (see
 * `encodeId()` in public/TrueSpordo.html):
 *
 *   id = base64(`HRP|${name}`) with +, /, = all replaced by "_"
 *
 * i.e. today's id literally encodes today's exact `name` string. That has
 * an important consequence for this mapping:
 *
 *   - If the other branch renames `FIELD_DATABASE[i].name` but leaves
 *     `.id` untouched (the normal/expected way to rename a display label
 *     without breaking a primary key), this map is unaffected — the ids
 *     below stay valid and only the EXACT_NAME_TO_FIELD_ID keys need
 *     updating to match the new display names (the ALIASES below already
 *     cover several of the known name corrections and can likely be
 *     promoted to exact matches and removed once that lands).
 *   - If instead the other branch (or a future refactor) regenerates `id`
 *     from the corrected `name` via encodeId(), every id in this file
 *     becomes stale simultaneously and this whole map must be
 *     regenerated from the merged FIELD_DATABASE. This is a real risk
 *     worth flagging explicitly to whoever merges that branch.
 *
 * Ids below were extracted directly from this branch's checkout of
 * public/TrueSpordo.html (2026-07-06) — not invented.
 */

/**
 * Exact match: HRPT page field name (as currently expected to render,
 * matching this branch's FIELD_DATABASE `name`) -> internal field_id.
 */
const EXACT_NAME_TO_FIELD_ID = {
  "Chelsea Waterside Basketball Court": "SFJQfENoZWxzZWEgV2F0ZXJzaWRlIEJhc2tldGJhbGwgQ291cnQ_",
  "Chelsea Waterside Athletic Field": "SFJQfENoZWxzZWEgV2F0ZXJzaWRlIEF0aGxldGljIEZpZWxk",
  "Pier 26 Sports Court": "SFJQfFBpZXIgMjYgU3BvcnRzIENvdXJ0",
  "Pier 25 Artificial Turf Field": "SFJQfFBpZXIgMjUgQXJ0aWZpY2lhbCBUdXJmIEZpZWxk",
  "Gansevoort Peninsula Playing Field": "SFJQfEdhbnNldm9vcnQgUGVuaW5zdWxhIFBsYXlpbmcgRmllbGQ_",
  "Pier 40 Courtyard East Field": "SFJQfFBpZXIgNDAgQ291cnR5YXJkIEVhc3QgRmllbGQ_",
  "Pier 40 Courtyard West Field": "SFJQfFBpZXIgNDAgQ291cnR5YXJkIFdlc3QgRmllbGQ_",
  "Pier 40 Indoor Field": "SFJQfFBpZXIgNDAgSW5kb29yIEZpZWxk",
  "Pier 40 Rooftop Field #1": "SFJQfFBpZXIgNDAgUm9vZnRvcCBGaWVsZCAjMQ__",
  "Pier 40 Rooftop Field #2": "SFJQfFBpZXIgNDAgUm9vZnRvcCBGaWVsZCAjMg__",
};

/**
 * Provisional aliases: page names CONFIRMED (this session, via a live
 * Cloudflare Worker fetch) to currently render on hudsonriverpark.org but
 * that don't literally match this branch's (stale) FIELD_DATABASE names.
 * Each is a best-effort "this is the same physical field, just named
 * differently on the live page than in our current DB" judgment call, NOT
 * a verified fact — flagged per-entry below.
 *
 * TODO(after fix/hrpt-field-names merges): once FIELD_DATABASE's `name`
 * fields are corrected, re-check each of these against the new names. If a
 * new name now matches the live page name exactly, delete that alias entry
 * (it'll resolve via EXACT_NAME_TO_FIELD_ID instead). If `id` values were
 * also regenerated by that branch, this entire file needs regenerating
 * from the merged FIELD_DATABASE (see file-level comment above).
 */
const ALIASES = [
  {
    pageName: "Pier 40 Indoor Youth Field",
    fieldId: EXACT_NAME_TO_FIELD_ID["Pier 40 Indoor Field"],
    note: "Live page name has a 'Youth' qualifier our DB name lacks. Assumed same physical field. NOT verified — could plausibly be a distinct youth-only sub-booking of Pier 40 Indoor Field.",
  },
  {
    pageName: "Pier 40 Rooftop Field #2 (Youth Only)",
    fieldId: EXACT_NAME_TO_FIELD_ID["Pier 40 Rooftop Field #2"],
    note: "Live page name has a '(Youth Only)' qualifier our DB name lacks. Assumed same physical field as Rooftop Field #2.",
  },
  {
    pageName: "Gansevoort Peninsula Athletic Field",
    fieldId: EXACT_NAME_TO_FIELD_ID["Gansevoort Peninsula Playing Field"],
    note: "Live page says 'Athletic Field', DB says 'Playing Field' — assumed to be the same rename the other branch is fixing.",
  },
  {
    pageName: "Pier 25 Turf Field",
    fieldId: EXACT_NAME_TO_FIELD_ID["Pier 25 Artificial Turf Field"],
    note: "Live page's shorter name assumed to refer to the same field as our 'Artificial Turf Field'.",
  },
];

const ALIAS_NAME_TO_FIELD_ID = Object.fromEntries(ALIASES.map((a) => [a.pageName, a.fieldId]));

function normalize(name) {
  return name.trim().toLowerCase().replace(/\s+/g, " ");
}

const NORMALIZED_EXACT = new Map(Object.entries(EXACT_NAME_TO_FIELD_ID).map(([k, v]) => [normalize(k), v]));
const NORMALIZED_ALIAS = new Map(Object.entries(ALIAS_NAME_TO_FIELD_ID).map(([k, v]) => [normalize(k), v]));

/**
 * @param {string} fieldNameOnPage
 * @returns {{ fieldId: string, matchType: 'exact'|'alias' } | null}
 */
function resolveFieldId(fieldNameOnPage) {
  if (!fieldNameOnPage) return null;
  const key = normalize(fieldNameOnPage);
  if (NORMALIZED_EXACT.has(key)) {
    return { fieldId: NORMALIZED_EXACT.get(key), matchType: "exact" };
  }
  if (NORMALIZED_ALIAS.has(key)) {
    return { fieldId: NORMALIZED_ALIAS.get(key), matchType: "alias" };
  }
  return null;
}

export { EXACT_NAME_TO_FIELD_ID, ALIASES, resolveFieldId };
